name: triade_app
description: App de produtividade baseado na Tríade do Tempo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shared_preferences: ^2.2.3
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP
  http: ^1.2.0

  # Datas
  intl: ^0.19.0

  # Gráficos
  fl_chart: ^0.66.0

  # UI
  cupertino_icons: ^1.0.6

  # Autenticação - Token seguro
  flutter_secure_storage: ^9.2.2

  # Upload de imagem
  image_picker: ^1.1.2

  # Áudio para feedback sonoro
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/triade_icon_nobg.png"
  
  # ÍCONE ADAPTATIVO (isso que resolve o problema!)
  adaptive_icon_foreground: "assets/triade_foreground.png"
  adaptive_icon_background: "#000000"
  
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/